---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/frontierhq/pre-commit-hooks
    rev: v0.1.0
    hooks:
      - id: uv-lock-check
      - id: make-test
