---
xpack.security.authc.providers.saml:
  saml1:
    order: 2
    realm: saml1
    description: "Log in with Microsoft Entra ID"
    icon: https://upload.wikimedia.org/wikipedia/commons/8/8c/Microsoft_Entra_ID_color_icon.svg
